"""customer id_number unique

Revision ID: 1d5b19032ff9
Revises: 819db488a258
Create Date: 2025-04-13 22:08:37.304102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5b19032ff9'
down_revision = '819db488a258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_id_number')
        batch_op.create_index(batch_op.f('ix_customers_id_number'), ['id_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id_number'))
        batch_op.create_index('ix_customers_id_number', ['id_number'], unique=False)

    # ### end Alembic commands ###
