"""actualizacion de tabla centro costo

Revision ID: 36df061c8c7a
Revises: b85e19bcdad5
Create Date: 2025-04-13 23:56:18.308661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36df061c8c7a'
down_revision = 'b85e19bcdad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_center_branch')
        batch_op.drop_index('ix_cost_center_name')
        batch_op.create_index(batch_op.f('ix_cost_center_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_center', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_center_name'))
        batch_op.create_index('ix_cost_center_name', ['name'], unique=False)
        batch_op.create_index('ix_cost_center_branch', ['branch'], unique=True)

    # ### end Alembic commands ###
