"""Initial migration

Revision ID: 3d09b87812f6
Revises: 
Create Date: 2025-04-08 23:08:40.929445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d09b87812f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_ticket_comments_created_at')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_tickets_created_at')
        batch_op.drop_index('ix_tickets_updated_at')
        batch_op.drop_constraint('tickets_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_to_id'], ['id'])
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tickets_ibfk_2', 'users', ['assigned_to'], ['id'])
        batch_op.create_index('ix_tickets_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_tickets_created_at', ['created_at'], unique=False)
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_comments_created_at', ['created_at'], unique=False)
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###
