"""Reset BD

Revision ID: 808f3e194185
Revises: 
Create Date: 2025-05-20 20:16:17.081540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '808f3e194185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.alter_column('is_internal',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.alter_column('is_internal',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
