"""actualizacion de tabla clientes

Revision ID: 819db488a258
Revises: e0cb95a001fa
Create Date: 2025-04-13 15:38:13.945834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '819db488a258'
down_revision = 'e0cb95a001fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=sa.String(length=300),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
