"""customer email not unique

Revision ID: a6d42d567e41
Revises: 1d5b19032ff9
Create Date: 2025-04-13 22:20:39.345305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d42d567e41'
down_revision = '1d5b19032ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_email', ['email'], unique=True)

    # ### end Alembic commands ###
