"""Add Assignment and AssetReturn models

Revision ID: f188f74b3918
Revises: 5f12d2606e49
Create Date: 2025-04-16 23:00:57.715396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f188f74b3918'
down_revision = '5f12d2606e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('rut')

    op.drop_table('customer')
    op.drop_table('assignment')
    with op.batch_alter_table('asset_return', schema=None) as batch_op:
        batch_op.drop_constraint('asset_return_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assignments', ['assignment_id'], ['id'])

    with op.batch_alter_table('assignment_customer', schema=None) as batch_op:
        batch_op.drop_constraint('assignment_customer_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('assignment_customer_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assignments', ['assignment_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('assignment_customer_ibfk_2', 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key('assignment_customer_ibfk_1', 'assignment', ['assignment_id'], ['id'])

    with op.batch_alter_table('asset_return', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_return_ibfk_1', 'assignment', ['assignment_id'], ['id'])

    op.create_table('assignment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='assignment_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='assignment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rut', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('rut', ['rut'], unique=True)

    op.drop_table('assignments')
    # ### end Alembic commands ###
